require 'string'
require 'utils.cjson'


global rpc = @record{}

function rpc.decode(msg: string): (*cJSON, integer, string)
  local matched, matched_strings= msg:match("(.-)\r\n\r\n(.*)")

  local header = matched_strings[1]
  local content = matched_strings[2]

  local result: *cJSON = cJSON_Parse(content)

  if not result then
    return result, 0, "Failed to parse JSON"
  end
  
  return result, #content, ""
end

function rpc.encode(obj: *cJSON)

end
